### ISSUE TITLE
Menu item order, coloring and warning 

### ISSUE THREAD

**Issue by henrywyh** [FYP-2021-2022-cloud-ide/App#76]
![image](https://user-images.githubusercontent.com/19517212/160523822-4beaedc9-6f97-4343-8b4e-ea1f83724afc.png)
environment

![image](https://user-images.githubusercontent.com/19517212/160523833-a79f601a-a478-4532-b890-7f51e41e0d43.png)
template 

and personal workspace

Operations like "delete", "update", "unpublish" should place further away from the menu icon to prevent accidental clicking 

"delete", "unpublish" should have a warning modal to confirm 

Operations like "delete","update", "unpublish" should have some colouring (red) or tip to alert the user performing such actions will delete all the existing containers

**Comment by HananoshikaYomaru** [comment]
duplicate with #60
