### ISSUE TITLE
template eye icon clickable

### ISSUE THREAD

**Issue by henrywyh** [FYP-2021-2022-cloud-ide/App#77]
![image](https://user-images.githubusercontent.com/19517212/160524461-1fe10c4d-ac5c-4a5e-b5c2-df975dd7adbc.png)
the template eye icon is intuitively clickable to publish/unpublish the template, 

And the unpublish step should have a warning modal pop up

**Comment by HananoshikaYomaru** [comment]
the eye will not be clickable but it will represented in a way that people will not think it is a button
