### ISSUE TITLE
formatting of message body

### ISSUE THREAD

**Issue by henrywyh** [FYP-2021-2022-cloud-ide/App#79]
![image](https://user-images.githubusercontent.com/19517212/160573512-76ac819f-7f77-4322-b16d-5e40afc3c02a.png)

original code: 
![image](https://user-images.githubusercontent.com/19517212/160573794-d2cafac1-d35d-440b-bc20-2baf70cb6e21.png)

The body of the message is originally formatted (with \t and \n)
But the body part does not show it

**Comment by HananoshikaYomaru** [comment]
I think the formatting needs to be handle in the backend. The frontend treat every message as markdown.
