### ISSUE TITLE
container info is not listed

### ISSUE THREAD

**Issue by henrywyh** [FYP-2021-2022-cloud-ide/App#86]
**Describe the bug**
container info is not listed

**To Reproduce**
1. start a workspace from a template or a personal workspace
2. go to the dashboard
 
**Expected behavior**
The container info is not listed, only title is there.

**Screenshots**
![image](https://user-images.githubusercontent.com/19517212/164165542-74c3f538-1703-4a69-8e91-7c8df61c5113.png)

**Comment by HananoshikaYomaru** [comment]
![CleanShot 2022-04-20 at 23 43 21](https://user-images.githubusercontent.com/43137033/164270176-fe60e1ea-9a17-44fa-9d73-aa4a02d9e0ff.png)

The container will only show title and course code. Description will not be shown because long sentences are not supposed to be displayed in this small card
